language: php
php:
  - '7.0'
env:
  - SYMFONY_VERSION="2.8.*"
services:
  - mysql
before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - php app/console doctrine:database:create --env=dev
  - php app/console doctrine:schema:create --env=dev
  - php app/console server:start
script:
  - phpunit -c app
after_script:
  - php app/console server:stop
notifications:
  email:
    - root@maxperei.info