get_budget:
    path:  /budgets/{id}
    defaults: { _controller: AppBundle:Budget:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_budgets:
    path:  /budgets
    defaults: { _controller: AppBundle:Budget:all, _format: ~ }
    requirements:
        _method: GET

post_budget:
    path:  /budgets
    defaults: { _controller: AppBundle:Budget:post, _format: ~ }
    requirements:
        _method: POST

put_budget:
    path:  /budgets/{id}
    defaults: { _controller: AppBundle:Budget:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_budget:
    path:  /budgets/{id}
    defaults: { _controller: AppBundle:Budget:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"