get_group:
    path:  /groups/{id}
    defaults: { _controller: AppBundle:Group:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_groups:
    path:  /groups
    defaults: { _controller: AppBundle:Group:all, _format: ~ }
    requirements:
        _method: GET

post_group:
    path:  /groups
    defaults: { _controller: AppBundle:Group:post, _format: ~ }
    requirements:
        _method: POST

put_group:
    path:  /groups/{id}
    defaults: { _controller: AppBundle:Group:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_group:
    path:  /groups/{id}
    defaults: { _controller: AppBundle:Group:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"