get_item:
    path:  /items/{id}
    defaults: { _controller: AppBundle:Item:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_items:
    path:  /items
    defaults: { _controller: AppBundle:Item:all, _format: ~ }
    requirements:
        _method: GET

post_item:
    path:  /items
    defaults: { _controller: AppBundle:Item:post, _format: ~ }
    requirements:
        _method: POST

put_item:
    path:  /items/{id}
    defaults: { _controller: AppBundle:Item:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_item:
    path:  /items/{id}
    defaults: { _controller: AppBundle:Item:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"