get_itemcategory:
    path:  /itemcategories/{id}
    defaults: { _controller: AppBundle:ItemCategory:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_itemcategories:
    path:  /itemcategories
    defaults: { _controller: AppBundle:ItemCategory:all, _format: ~ }
    requirements:
        _method: GET

post_itemcategory:
    path:  /itemcategories
    defaults: { _controller: AppBundle:ItemCategory:post, _format: ~ }
    requirements:
        _method: POST

put_itemcategory:
    path:  /itemcategories/{id}
    defaults: { _controller: AppBundle:ItemCategory:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_itemcategory:
    path:  /itemcategories/{id}
    defaults: { _controller: AppBundle:ItemCategory:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"