get_luggage:
    path:  /luggages/{id}
    defaults: { _controller: AppBundle:Luggage:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_luggages:
    path:  /luggages
    defaults: { _controller: AppBundle:Luggage:all, _format: ~ }
    requirements:
        _method: GET

post_luggage:
    path:  /luggages
    defaults: { _controller: AppBundle:Luggage:post, _format: ~ }
    requirements:
        _method: POST

put_luggage:
    path:  /luggages/{id}
    defaults: { _controller: AppBundle:Luggage:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_luggage:
    path:  /luggages/{id}
    defaults: { _controller: AppBundle:Luggage:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"