get_outgo:
    path:  /outgos/{id}
    defaults: { _controller: AppBundle:Outgo:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_outgos:
    path:  /outgos
    defaults: { _controller: AppBundle:Outgo:all, _format: ~ }
    requirements:
        _method: GET

post_outgo:
    path:  /outgos
    defaults: { _controller: AppBundle:Outgo:post, _format: ~ }
    requirements:
        _method: POST

put_outgo:
    path:  /outgos/{id}
    defaults: { _controller: AppBundle:Outgo:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_outgo:
    path:  /outgos/{id}
    defaults: { _controller: AppBundle:Outgo:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"