get_outgocategory:
    path:  /outgocategories/{id}
    defaults: { _controller: AppBundle:OutgoCategory:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_outgocategories:
    path:  /outgocategories
    defaults: { _controller: AppBundle:OutgoCategory:all, _format: ~ }
    requirements:
        _method: GET

post_outgocategory:
    path:  /outgocategories
    defaults: { _controller: AppBundle:OutgoCategory:post, _format: ~ }
    requirements:
        _method: POST

put_outgocategory:
    path:  /outgocategories/{id}
    defaults: { _controller: AppBundle:OutgoCategory:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_outgocategory:
    path:  /outgocategories/{id}
    defaults: { _controller: AppBundle:OutgoCategory:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"