get_project:
    path:  /projects/{id}
    defaults: { _controller: AppBundle:Project:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_projects:
    path:  /projects
    defaults: { _controller: AppBundle:Project:all, _format: ~ }
    requirements:
        _method: GET

post_project:
    path:  /projects
    defaults: { _controller: AppBundle:Project:post, _format: ~ }
    requirements:
        _method: POST

put_project:
    path:  /projects/{id}
    defaults: { _controller: AppBundle:Project:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_project:
    path:  /projects/{id}
    defaults: { _controller: AppBundle:Project:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"