get_travelogue:
    path:  /travelogues/{id}
    defaults: { _controller: AppBundle:Travelogue:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_travelogues:
    path:  /travelogues
    defaults: { _controller: AppBundle:Travelogue:all, _format: ~ }
    requirements:
        _method: GET

post_travelogue:
    path:  /travelogues
    defaults: { _controller: AppBundle:Travelogue:post, _format: ~ }
    requirements:
        _method: POST

put_travelogue:
    path:  /travelogues/{id}
    defaults: { _controller: AppBundle:Travelogue:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_travelogue:
    path:  /travelogues/{id}
    defaults: { _controller: AppBundle:Travelogue:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"