get_userpref:
    path:  /userprefs/{id}
    defaults: { _controller: AppBundle:UserPref:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"

get_userprefs:
    path:  /userprefs
    defaults: { _controller: AppBundle:UserPref:all, _format: ~ }
    requirements:
        _method: GET

post_userpref:
    path:  /userprefs
    defaults: { _controller: AppBundle:UserPref:post, _format: ~ }
    requirements:
        _method: POST

put_userpref:
    path:  /userprefs/{id}
    defaults: { _controller: AppBundle:UserPref:put, _format: ~ }
    requirements:
        _method: PUT
        id: "\d+"

delete_userpref:
    path:  /userprefs/{id}
    defaults: { _controller: AppBundle:UserPref:delete, _format: ~ }
    requirements:
        _method: DELETE
        id: "\d+"